name: Main

on:
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate Changelog
              id: changelog
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ github.token }}
                  tag: ${{ github.ref_name }}
                  writeToFile: false
            - uses: montudor/action-zip@v1
              with:
                  args: zip -r curve_terrain.zip LICENSE addons/curve_terrain/
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      curve_terrain.zip
                  body: ${{steps.changelog.outputs.changes}}
